# Generated by Django 4.2.21 on 2025-05-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='favorite_cars',
            field=models.ManyToManyField(related_name='interested_buyers', to='salon.car', verbose_name='Избранные автомобили'),
        ),
    ]
