# Generated by Django 4.2.21 on 2025-05-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_buyer_favorite_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='real_value',
            field=models.IntegerField(default='0'),
        ),
    ]
